name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install flake8 pytest pandas  # Instala flake8, pytest e pandas explicitamente

    - name: Check flake8 and pytest installation
      run: |
        which flake8  # Verifica se o flake8 está no PATH
        flake8 --version  # Mostra a versão do flake8
        which pytest  # Verifica se o pytest está no PATH
        pytest --version  # Mostra a versão do pytest
        python -c "import pandas; print(pandas.__version__)"  # Verifica se o pandas está instalado

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        pytest
